# Generated by Django 5.1.2 on 2024-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leapyear_count', models.IntegerField(default=0)),
                ('non_leapyear_count', models.IntegerField(default=0)),
            ],
        ),
    ]
